version: 2
updates:

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "[GitHub] "
      include: "scope"
    open-pull-requests-limit: 2
    cooldown:
      default-days: 7
    labels:
      - "dependencies"
      - "bot"

  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "[requirements] "
      include: scope
    labels:
      - "dependencies"
      - "bot"
    cooldown:
      default-days: 7